#define RTDATA_H


// KernelSpike
#define KERNELSPIKE_TICK_PERIOD 1000000
#define KERNELSPIKE_TASK_PRIORITY 1
#define KERNELSPIKE_STACK_SIZE 10000
#define KERNELSPIKE_CPUID 2
#define KERNELSPIKE_PASS_DATA 0
#define KERNELSPIKE_SIGNAL 0
#define KERNELSPIKE_USES_FLOATING_POINT 1

//Recorder
