#ifndef SHARED_MEMORY_ADDITIONAL_DATA_H
#define SHARED_MEMORY_ADDITIONAL_DATA_H




#define MAX_NUM_OF_SHM_ADDITIONAL_DATA			10


#define 	SHM_ADDITIONAL_DATA_NULL						0
#define 	SHM_ADDITIONAL_DATA_TRIALS_DATA					1
#define 	SHM_ADDITIONAL_DATA_EXP_ENVI_DATA				2
#define 	SHM_ADDITIONAL_DATA_MOV_OBJ_DATA				3







#endif
