#ifndef SHARED_MEMORY_ADDITIONAL_DATA_H
#define SHARED_MEMORY_ADDITIONAL_DATA_H




#define MAX_NUM_OF_SHM_ADDITIONAL_DATA			10


#define 	SHM_ADD_DATA_NULL						0
#define 	SHM_ADD_DATA_TRIAL_STATUS				1
#define 	SHM_ADD_DATA_EXP_ENVI_COMMAND			2
#define 	SHM_ADD_DATA_EXP_ENVI_EVENT			3
#define 	SHM_ADD_DATA_MOV_OBJ_COMMAND			4
#define 	SHM_ADD_DATA_MOV_OBJ_EVENT			5






#endif
