#ifndef SHM_NUM_H
#define SHM_NUM_H

#include "../RtTasksData/RtTasksData.h"

// NOTE:    SEMAPHORE AND SHARED MEMORY CANNOT USE THE SAME OBJECT NUMBER 

///////////////  SEMAPHORE /////////////////////////////////
#define SEM_NUM_EXP_ENVI_RX_BUFFER			101
#define SEM_NUM_EXP_ENVI_TX_BUFFER			102







///////////////  SHARED MEMORY /////////////////////////////////

#define SHM_NUM_RT_TASKS_DATA							200

#define SHM_NUM_KERNEL_SPIKE_DAQ_MWA_DATA				201
#define SHM_NUM_KERNEL_SPIKE_RECORDING_DATA			202
#define SHM_NUM_KERNEL_SPIKE_FILTERED_RECORDING_DATA	203
#define SHM_NUM_KERNEL_SPIKE_SPIKE_THRESHOLDING		204
#define SHM_NUM_KERNEL_SPIKE_BLUE_SPIKE_TIME_STAMP	205
#define SHM_NUM_KERNEL_SPIKE_SPIKE_TIME_STAMP			206
#define SHM_NUM_KERNEL_SPIKE_TEMPLATE_MATCHING		207
#define SHM_NUM_KERNEL_SPIKE_FILTER_CTRL				208

#define SHM_NUM_EXP_ENVI_RX_BUFFER			251   // should be shorter than or equal to 6 for correct shm numbering
#define SHM_NUM_EXP_ENVI_TX_BUFFER			252

#define SHM_NUM_DAQ_CONFIG_2_KERNEL_SPIKE			401
#define SHM_NUM_FILTER_CTRL_2_KERNEL_SPIKE			402
#define SHM_NUM_SPIKE_THRES_2_KERNEL_SPIKE			403	
#define SHM_NUM_TEMPLATE_MATCHING_2_KERNEL_SPIKE	404

#define SHM_NUM_TRIAL_HAND_2_EXP_ENVI_HAND			501			
#define SHM_NUM_TRIAL_HAND_2_MOV_OBJ_HAND			502
#define SHM_NUM_TRIAL_HAND_2_NEURAL_NET			503
#define SHM_NUM_TRIAL_HAND_2_SPIKE_GEN				504
#define SHM_NUM_TRIAL_HAND_2_NEU_REC_HAND			505

#define SHM_NUM_EXP_ENVI_HAND_2_TRIAL_HAND			520


#define SHM_NUM_MOV_OBJ_HAND_2_NEURAL_NET			541
#define NUM_OF_MOV_OBJ_HAND_2_NEURAL_NET_MSG_BUFFERS 		IZ_PS_NETWORK_SIM_NUM_OF_DEDICATED_CPUS*MAX_NUM_OF_CPU_THREADS_PER_CPU
#define SHM_NUM_MOV_OBJ_HAND_2_TRIAL_HAND			SHM_NUM_MOV_OBJ_HAND_2_NEURAL_NET+NUM_OF_MOV_OBJ_HAND_2_NEURAL_NET_MSG_BUFFERS+1			


#define SHM_NUM_NEURAL_NET_2_MOV_OBJ_HAND			561	
#define SHM_NUM_NEURAL_NET_2_TRIAL_HAND			562

#define SHM_NUM_SPIKE_GEN_2_TRIAL_HAND				581

#define SHM_NUM_NEU_REC_HAND_2_TRIAL_HAND			591

#endif
