#ifndef KERNEL_SPIKE_SHARED_MEM_H
#define KERNEL_SPIKE_SHARED_MEM_H


#define KERNEL_SPIKE_DAQ_MWA_DATA_SHM_NAME				"KSDQMW"
#define KERNEL_SPIKE_RECORDING_DATA_SHM_NAME				"KSRCDT"
#define KERNEL_SPIKE_FILTERED_RECORDING_DATA_SHM_NAME	"KSFRDT"
#define KERNEL_SPIKE_SPIKE_THRESHOLDING_SHM_NAME			"KSSPTH"
#define KERNEL_SPIKE_BLUE_SPIKE_TIME_STAMP_SHM_NAME		"KSBSTS"
#define KERNEL_SPIKE_SPIKE_TIME_STAMP_SHM_NAME				"KSSTS"
#define KERNEL_SPIKE_TEMPLATE_MATHCHING_SHM_NAME			"KSTMAT"
#define KERNEL_SPIKE_FILTER_CTRL_SHM_NAME					"KSFILTC"



#endif
